In [1]:
# importing libraries
import pandas as pd
import numpy as np

In [2]:
# importing selenium and webdriver
import selenium
from selenium import webdriver

import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

# importing required exceptions which needed to be handled
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementNotInteractableException

# Scraping from CarTrade Website

In [3]:
# activating the chrome browser
driver=webdriver.Chrome("C:/Users/jprat/Downloads/chromedriver_win32 (1)/chromedriver.exe")

In [4]:
# opening used cars page on website
driver.get('https://www.cartrade.com/buy-used-cars/#sc=-1&so=-1&pn=1')
time.sleep(8)
# closing pop-up
close=driver.find_element_by_xpath("//a[@id='citybandclose']")
close.click()

In [5]:
# extracting used cars url
cars_url = []
for page in range(0,100): # extracting used cars url from page1 to page 100
    for i in driver.find_elements_by_xpath("//h2[@class='h2heading truncate']/a"):
        cars_url.append(i.get_attribute('href'))
    try: # to enter next page   
        nxt_page=driver.find_element_by_xpath("//li[@class='next']/a").get_attribute('href')
        driver.get(nxt_page)
        delay=8
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH,"//a[@id='citybandclose']")))
        close=driver.find_element_by_xpath("//a[@id='citybandclose']") # closing pop-up
        close.click()
        delay=8
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH,"//h2[@class='h2heading truncate']/a")))
    except NoSuchElementException:
        break

In [6]:
len(cars_url)

2408

In [7]:
%%time

# Let's create empty lists to store necessary information
brand_model1 = []
fuel1 = []
kms_driven1 = []
no_of_owners1 = []
make_year1 = []
price1 = []

for url in cars_url[:600]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//h1[@class='h_2']")))
    except:
        continue
    
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//h1[@class='h_2']")
        brand_model1.append(bm.text.replace('Used ',''))
    except NoSuchElementException:
        brand_model1.append(np.NaN)
    
#     extracting FUEL TYPE
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[2]/td[2]"):
            fuel1.append(i.text)
    except NoSuchElementException:
        fuel1.append(np.NaN)
    
#     extracting KMS Driven
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[3]/td[2]"):
            kms_driven1.append(i.text.replace(' Kms',''))
    except NoSuchElementException:
        kms_driven1.append(np.NaN)
    
#     extracting NUMBER OF OWNERS
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[5]/td[2]"):
            no_of_owners1.append(i.text)
    except NoSuchElementException:
        no_of_owners1.append(np.NaN)
    
#     extracting MANUFACTURING YEAR
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[8]/td[2]"):
            make_year1.append(i.text)
    except NoSuchElementException:
        make_year1.append(np.NaN)
    
#     extracting price
    try:
        for i in driver.find_elements_by_xpath("//div[@class='pull-left']/span[2]"):
            price1.append(i.get_attribute('content'))
    except NoSuchElementException:
        price1.append(np.NaN)

Wall time: 36min 36s

In [8]:
# Let's create empty lists to store necessary information
brand_model2 = []
fuel2 = []
kms_driven2 = []
no_of_owners2 = []
make_year2 = []
price2 = []

for url in cars_url[600:1200]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//h1[@class='h_2']")))
    except:
        continue
    
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//h1[@class='h_2']")
        brand_model2.append(bm.text.replace('Used ',''))
    except NoSuchElementException:
        brand_model2.append(np.NaN)
    
#     extracting FUEL TYPE
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[2]/td[2]"):
            fuel2.append(i.text)
    except NoSuchElementException:
        fuel2.append(np.NaN)
    
#     extracting KMS Driven
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[3]/td[2]"):
            kms_driven2.append(i.text.replace(' Kms',''))
    except NoSuchElementException:
        kms_driven2.append(np.NaN)
    
#     extracting NUMBER OF OWNERS
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[5]/td[2]"):
            no_of_owners2.append(i.text)
    except NoSuchElementException:
        no_of_owners2.append(np.NaN)
    
#     extracting MANUFACTURING YEAR
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[8]/td[2]"):
            make_year2.append(i.text)
    except NoSuchElementException:
        make_year2.append(np.NaN)
    
#     extracting price
    try:
        for i in driver.find_elements_by_xpath("//div[@class='pull-left']/span[2]"):
            price2.append(i.get_attribute('content'))
    except NoSuchElementException:
        price2.append(np.NaN)

In [9]:
# Let's create empty lists to store necessary information
brand_model3 = []
fuel3 = []
kms_driven3 = []
no_of_owners3 = []
make_year3 = []
price3 = []

for url in cars_url[1200:1800]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//h1[@class='h_2']")))
    except:
        continue
    
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//h1[@class='h_2']")
        brand_model3.append(bm.text.replace('Used ',''))
    except NoSuchElementException:
        brand_model3.append(np.NaN)
    
#     extracting FUEL TYPE
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[2]/td[2]"):
            fuel3.append(i.text)
    except NoSuchElementException:
        fuel3.append(np.NaN)
    
#     extracting KMS Driven
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[3]/td[2]"):
            kms_driven3.append(i.text.replace(' Kms',''))
    except NoSuchElementException:
        kms_driven3.append(np.NaN)
    
#     extracting NUMBER OF OWNERS
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[5]/td[2]"):
            no_of_owners3.append(i.text)
    except NoSuchElementException:
        no_of_owners3.append(np.NaN)
    
#     extracting MANUFACTURING YEAR
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[8]/td[2]"):
            make_year3.append(i.text)
    except NoSuchElementException:
        make_year3.append(np.NaN)
    
#     extracting price
    try:
        for i in driver.find_elements_by_xpath("//div[@class='pull-left']/span[2]"):
            price3.append(i.get_attribute('content'))
    except NoSuchElementException:
        price3.append(np.NaN)

In [10]:
# Let's create empty lists to store necessary information
brand_model4 = []
fuel4 = []
kms_driven4 = []
no_of_owners4 = []
make_year4 = []
price4 = []

for url in cars_url[1800:2406]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//h1[@class='h_2']")))
    except:
        continue
    
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//h1[@class='h_2']")
        brand_model4.append(bm.text.replace('Used ',''))
    except NoSuchElementException:
        brand_model4.append(np.NaN)
    
#     extracting FUEL TYPE
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[2]/td[2]"):
            fuel4.append(i.text)
    except NoSuchElementException:
        fuel4.append(np.NaN)
    
#     extracting KMS Driven
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[3]/td[2]"):
            kms_driven4.append(i.text.replace(' Kms',''))
    except NoSuchElementException:
        kms_driven4.append(np.NaN)
    
#     extracting NUMBER OF OWNERS
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[5]/td[2]"):
            no_of_owners4.append(i.text)
    except NoSuchElementException:
        no_of_owners4.append(np.NaN)
    
#     extracting MANUFACTURING YEAR
    try:
        for i in driver.find_elements_by_xpath("//table[@class='v_table']/tbody/tr[8]/td[2]"):
            make_year4.append(i.text)
    except NoSuchElementException:
        make_year4.append(np.NaN)
    
#     extracting price
    try:
        for i in driver.find_elements_by_xpath("//div[@class='pull-left']/span[2]"):
            price4.append(i.get_attribute('content'))
    except NoSuchElementException:
        price4.append(np.NaN)

In [12]:
# adding extracted chunks of car details
brand_model = brand_model1 + brand_model2 + brand_model3 + brand_model4
fuel = fuel1 + fuel2 + fuel3 + fuel4
kms_driven = kms_driven1 + kms_driven2 + kms_driven3 + kms_driven4
no_of_owners = no_of_owners1 + no_of_owners2 + no_of_owners3 + no_of_owners4
make_year = make_year1 + make_year2 + make_year3 + make_year4
price = price1 + price2 + price3 + price4

In [13]:
# storing data in dataframe
df = pd.DataFrame({})
df['Brand_Model'] = brand_model
df['Fuel'] = fuel
df['Kms_driven'] = kms_driven
df['No_of_owners'] = no_of_owners
df['Make_year'] = make_year
df['Price'] = price

In [14]:
df

,Brand_Model,Fuel,Kms_driven,No_of_owners,Make_year,Price
0,Hyundai i10 [2007-2010] in Hyderabad,Petrol,"82,967",First,2009,280000
1,Maruti Suzuki Baleno [2015-2019] in Pune,Petrol,"29,687",First,2016,510000
2,Maruti Suzuki Dzire [2017-2020] in Mumbai,Diesel,"25,899",First,2018,795000
3,Tata Tiago [2016-2020] in Lakhimpur Kheri,Petrol,"59,000",First,2016,350000
4,Hyundai Creta [2019-2020] in Jaipur,Diesel,"42,300",First,2019,1590000
...,...,...,...,...,...,...
2393,Toyota Fortuner [2012-2016] in Ahmedabad,Diesel,"1,42,000",Second,2014,1250000
2394,Hyundai Verna [2011-2015] in Bangalore,Diesel,"1,24,000",First,2011,545000
2395,Mercedes-Benz C-Class [2010-2011] in Delhi,Diesel,"99,000",First,2011,1090000
2396,Maruti Suzuki Swift [2011-2014] in Mumbai,Petrol,"22,000",First,2014,445000
2397,Ford Endeavour [2009-2014] in Indore,Diesel,"97,000",Second,2010,580000

In [15]:
# saving data
df.to_csv('CarTrade.csv', index=False)

# Scraping from Cars24 Website

In [3]:
# activating the chrome browser
driver=webdriver.Chrome("C:\\chromedriver.exe")

In [4]:
# opening used cars page on website
driver.get('https://www.cars24.com/buy-used-car?sort=P&storeCityId=2&pinId=110001')
time.sleep(8)

In [5]:
# extracting used cars url
cars_url = []
for i in driver.find_elements_by_xpath("//a[@class='_20d39']"):
    cars_url.append(i.get_attribute('href'))

In [6]:
len(cars_url)

1419

In [7]:
%%time

# Let's create empty lists to store necessary information
brand_model1 = []
fuel1 = []
kms_driven1 = []
no_of_owners1 = []
make_year1 = []
price1 = []

for url in cars_url[:500]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//p[@class='_3Uk5w']")))
    except:
        continue
    
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//p[@class='_3Uk5w']")
        brand_model1.append(bm.text)
    except NoSuchElementException:
        brand_model1.append(np.NaN)
    
#     extracting FUEL TYPE, KMS Driven, NUMBER OF OWNERS, MANUFACTURING YEAR
    info = []
    try:
        for i in driver.find_elements_by_xpath("//div[@class='media-body _3fGRT']/p"):
            info.append(i.text)
        fuel1.append(info[3])            # extracting FUEL TYPE
        kms_driven1.append(info[0])      # extracting KMS Driven
        no_of_owners1.append(info[2])    # extracting NUMBER OF OWNERS
        make_year1.append(info[1])       # extracting MANUFACTURING YEAR
    except NoSuchElementException:
        fuel1.append(np.NaN)            
        kms_driven1.append(np.NaN)      
        no_of_owners1.append(np.NaN)    
        make_year1.append(np.NaN)
    
#     extracting price
    try:
        for i in driver.find_elements_by_xpath("//h4[@class='_3AzX6']"):
            price1.append(i.text.replace('₹ ',''))
    except NoSuchElementException:
        price1.append(np.NaN)

Wall time: 45min 42s

In [8]:
# Let's create empty lists to store necessary information
brand_model2 = []
fuel2 = []
kms_driven2 = []
no_of_owners2 = []
make_year2 = []
price2 = []

for url in cars_url[500:1000]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//p[@class='_3Uk5w']")))
    except:
        continue
    
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//p[@class='_3Uk5w']")
        brand_model2.append(bm.text)
    except NoSuchElementException:
        brand_model2.append(np.NaN)
    
#     extracting FUEL TYPE, KMS Driven, NUMBER OF OWNERS, MANUFACTURING YEAR
    info = []
    try:
        for i in driver.find_elements_by_xpath("//div[@class='media-body _3fGRT']/p"):
            info.append(i.text)
        fuel2.append(info[3])            # extracting FUEL TYPE
        kms_driven2.append(info[0])      # extracting KMS Driven
        no_of_owners2.append(info[2])    # extracting NUMBER OF OWNERS
        make_year2.append(info[1])       # extracting MANUFACTURING YEAR
    except NoSuchElementException:
        fuel2.append(np.NaN)            
        kms_driven2.append(np.NaN)      
        no_of_owners2.append(np.NaN)    
        make_year2.append(np.NaN)
    
#     extracting price
    try:
        for i in driver.find_elements_by_xpath("//h4[@class='_3AzX6']"):
            price2.append(i.text.replace('₹ ',''))
    except NoSuchElementException:
        price2.append(np.NaN)

In [9]:
# Let's create empty lists to store necessary information
brand_model3 = []
fuel3 = []
kms_driven3 = []
no_of_owners3 = []
make_year3 = []
price3 = []

for url in cars_url[1000:1417]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//p[@class='_3Uk5w']")))
    except:
        continue
    
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//p[@class='_3Uk5w']")
        brand_model3.append(bm.text)
    except NoSuchElementException:
        brand_model3.append(np.NaN)
    
#     extracting FUEL TYPE, KMS Driven, NUMBER OF OWNERS, MANUFACTURING YEAR
    info = []
    try:
        for i in driver.find_elements_by_xpath("//div[@class='media-body _3fGRT']/p"):
            info.append(i.text)
        fuel3.append(info[3])            # extracting FUEL TYPE
        kms_driven3.append(info[0])      # extracting KMS Driven
        no_of_owners3.append(info[2])    # extracting NUMBER OF OWNERS
        make_year3.append(info[1])       # extracting MANUFACTURING YEAR
    except NoSuchElementException:
        fuel3.append(np.NaN)            
        kms_driven3.append(np.NaN)      
        no_of_owners3.append(np.NaN)    
        make_year3.append(np.NaN)
    
#     extracting price
    try:
        for i in driver.find_elements_by_xpath("//h4[@class='_3AzX6']"):
            price3.append(i.text.replace('₹ ',''))
    except NoSuchElementException:
        price3.append(np.NaN)

In [10]:
# adding extracted chunks of car details
brand_model = brand_model1 + brand_model2 + brand_model3
fuel = fuel1 + fuel2 + fuel3
kms_driven = kms_driven1 + kms_driven2 + kms_driven3
no_of_owners = no_of_owners1 + no_of_owners2 + no_of_owners3
make_year = make_year1 + make_year2 + make_year3
price = price1 + price2 + price3

In [11]:
# storing data in dataframe
df = pd.DataFrame({})
df['Brand_Model'] = brand_model
df['Fuel'] = fuel
df['Kms_driven'] = kms_driven
df['No_of_owners'] = no_of_owners
df['Make_year'] = make_year
df['Price'] = price

In [12]:
df

,Brand_Model,Fuel,Kms_driven,No_of_owners,Make_year,Price
0,2011 Maruti Wagon R 1.0 VXI,Petrol,"12,501 km",First Owner,March 2011,"2,39,899"
1,2010 Maruti Alto LXI,Petrol,"29,166 km",First Owner,January 2010,"1,58,099"
2,2017 Renault Kwid CLIMBER 1.0,Petrol,"15,032 km",Second Owner,March 2017,"2,77,699"
3,2016 Maruti Baleno DELTA 1.2 K12,Petrol,"26,568 km",Second Owner,June 2016,"4,78,799"
4,2018 Maruti Alto 800 LXI,Petrol,"15,838 km",First Owner,April 2018,"3,13,799"
...,...,...,...,...,...,...
1387,2012 Toyota Etios GD,Diesel,"2,12,989 km",First Owner,April 2012,"2,38,999"
1388,2015 Toyota Etios CROSS VD,Diesel,"1,10,780 km",First Owner,March 2015,"3,41,299"
1389,2012 Toyota Fortuner 3.0 AT 4X2,Diesel,"1,54,591 km",Second Owner,June 2012,"12,60,799"
1390,2012 Toyota Fortuner 3.0 AT 4X2,Diesel,"1,21,632 km",First Owner,April 2012,"10,62,399"
1391,2014 Toyota Fortuner 3.0 AT 4X2,Diesel,"1,11,327 km",Second Owner,July 2014,"12,96,299"

In [14]:
# saving data
df.to_csv('Cars24.csv', index=False)

# Scraping from Droom Website

In [3]:
# activating the chrome browser
driver=webdriver.Chrome("C:\\chromedriver.exe")

In [4]:
# opening used cars page on website
driver.get('https://droom.in/cars/used')
time.sleep(8)

In [6]:
# loading more used cars
load_more = driver.find_element_by_xpath("//div[@id='loadMore']/button")
load_more.click()

In [11]:
# extracting used cars url
cars_url = []
for i in driver.find_elements_by_xpath("//a[@class='d-text-black']"):
    cars_url.append(i.get_attribute('href'))

In [12]:
len(cars_url)

1521

In [13]:
%%time

# Let's create empty lists to store necessary information
brand_model1 = []
fuel1 = []
kms_driven1 = []
no_of_owners1 = []
make_year1 = []
price1 = []

for url in cars_url[:500]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")))
    except:
        continue
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")
        brand_model1.append(bm.text)
    except NoSuchElementException:
        brand_model1.append(np.NaN)
    
#     extracting FUEL TYPE, KMS Driven, NUMBER OF OWNERS    
    info = []
    try:
        for i in driver.find_elements_by_xpath("//div[@class='d-margin-top-2 d-text-gray d-font-size-12']"):
            info.append(i.text)
        fuel1.append(info[3])            # extracting FUEL TYPE
        kms_driven1.append(info[1])      # extracting KMS Driven
        no_of_owners1.append(info[0])    # extracting NUMBER OF OWNERS
    except NoSuchElementException:
        fuel1.append(np.NaN)            
        kms_driven1.append(np.NaN)      
        no_of_owners1.append(np.NaN)
    
#     extracting MANUFACTURING YEAR    
    try:
        my=driver.find_element_by_xpath("//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")
        make_year1.append(my.text.split()[-1])
    except NoSuchElementException:
        make_year1.append(np.NaN)
    
#     extracting price    
    try:
        p=driver.find_element_by_xpath("//div[@class=' d-font-size-22']")
        price1.append(p.text.replace('₹ ','').replace(',',''))    
    except NoSuchElementException:
        p=driver.find_element_by_xpath("//div[@class=' d-text-decoration-line-through  d-font-size-22']")
        price1.append(p.text.replace('₹ ','').replace(',',''))
    except:
        price1.append(np.NaN)

Wall time: 43min 10s

In [17]:
%%time

# Let's create empty lists to store necessary information
brand_model2 = []
fuel2 = []
kms_driven2 = []
no_of_owners2 = []
make_year2 = []
price2 = []

for url in cars_url[500:1000]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//div[@class='d-margin-top-2 d-text-gray d-font-size-12']")))
    except:
        continue
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")
        brand_model2.append(bm.text)
    except NoSuchElementException:
        brand_model2.append(np.NaN)
    
#     extracting FUEL TYPE, KMS Driven, NUMBER OF OWNERS    
    info = []
    try:
        for i in driver.find_elements_by_xpath("//div[@class='d-margin-top-2 d-text-gray d-font-size-12']"):
            info.append(i.text)
        fuel2.append(info[3])            # extracting FUEL TYPE
        kms_driven2.append(info[1])      # extracting KMS Driven
        no_of_owners2.append(info[0])    # extracting NUMBER OF OWNERS
    except NoSuchElementException:
        fuel2.append(np.NaN)            
        kms_driven2.append(np.NaN)      
        no_of_owners2.append(np.NaN)
    
#     extracting MANUFACTURING YEAR    
    try:
        my=driver.find_element_by_xpath("//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")
        make_year2.append(my.text.split()[-1])
    except NoSuchElementException:
        make_year2.append(np.NaN)
    
#     extracting price    
    try:
        p=driver.find_element_by_xpath("//div[@class=' d-font-size-22']")
        price2.append(p.text.replace('₹ ','').replace(',',''))    
    except NoSuchElementException:
        p=driver.find_element_by_xpath("//div[@class=' d-text-decoration-line-through  d-font-size-22']")
        price2.append(p.text.replace('₹ ','').replace(',',''))
    except:
        price2.append(np.NaN)

Wall time: 49min 44s

In [15]:
%%time

# Let's create empty lists to store necessary information
brand_model3 = []
fuel3 = []
kms_driven3 = []
no_of_owners3 = []
make_year3 = []
price3 = []

for url in cars_url[1000:1519]: # extracting cars details in chunks
    driver.get(url) # opening the car page
    try:
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH, "//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")))
    except:
        continue
#     extracting brand and model
    try:
        bm=driver.find_element_by_xpath("//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")
        brand_model3.append(bm.text)
    except NoSuchElementException:
        brand_model3.append(np.NaN)
    
#     extracting FUEL TYPE, KMS Driven, NUMBER OF OWNERS    
    info = []
    try:
        for i in driver.find_elements_by_xpath("//div[@class='d-margin-top-2 d-text-gray d-font-size-12']"):
            info.append(i.text)
        fuel3.append(info[3])            # extracting FUEL TYPE
        kms_driven3.append(info[1])      # extracting KMS Driven
        no_of_owners3.append(info[0])    # extracting NUMBER OF OWNERS
    except NoSuchElementException:
        fuel3.append(np.NaN)            
        kms_driven3.append(np.NaN)      
        no_of_owners3.append(np.NaN)
    
#     extracting MANUFACTURING YEAR    
    try:
        my=driver.find_element_by_xpath("//h1[@class='d-font-weight-500 d-font-size-22 d-text-dark d-margin-top-0']")
        make_year3.append(my.text.split()[-1])
    except NoSuchElementException:
        make_year3.append(np.NaN)
    
#     extracting price    
    try:
        p=driver.find_element_by_xpath("//div[@class=' d-font-size-22']")
        price3.append(p.text.replace('₹ ','').replace(',',''))    
    except NoSuchElementException:
        p=driver.find_element_by_xpath("//div[@class=' d-text-decoration-line-through  d-font-size-22']")
        price3.append(p.text.replace('₹ ','').replace(',',''))
    except:
        price3.append(np.NaN)

Wall time: 50min 36s

In [18]:
# adding extracted chunks of car details
brand_model = brand_model1 + brand_model2 + brand_model3
fuel = fuel1 + fuel2 + fuel3
kms_driven = kms_driven1 + kms_driven2 + kms_driven3
no_of_owners = no_of_owners1 + no_of_owners2 + no_of_owners3
make_year = make_year1 + make_year2 + make_year3
price = price1 + price2 + price3

In [19]:
# storing data in dataframe
df = pd.DataFrame({})
df['Brand_Model'] = brand_model
df['Fuel'] = fuel
df['Kms_driven'] = kms_driven
df['No_of_owners'] = no_of_owners
df['Make_year'] = make_year
df['Price'] = price

df

,Brand_Model,Fuel,Kms_driven,No_of_owners,Make_year,Price
0,Audi Q5 2.0 TDI PREMIUM PLUS 2014,Diesel,146000 Km,First Owner,2014,1600000
1,Tata Tiago Revotron XZA 2017,Petrol,14000 Km,First Owner,2017,550000
2,Honda Civic 1.8S AT 2010,Petrol,92000 Km,Second Owner,2010,230000
3,Fiat Linea EMOTION 1.4 2010,Petrol,100000 Km,Third Owner,2010,210000
4,Toyota Corolla Altis J DIESEL 2013,Diesel,68000 Km,First Owner,2013,530000
...,...,...,...,...,...,...
1512,Maruti Suzuki Ciaz VDi+ SHVS 2015,Diesel,81000 Km,First Owner,2015,570000
1513,Hyundai Elite i20 Magna Executive 1.2 2019,Petrol,34500 Km,First Owner,2019,610000
1514,Maruti Suzuki ALTO 800 LXi (O) 2017,Petrol,77800 Km,First Owner,2017,270000
1515,Maruti Suzuki Alto LXi 2009,Petrol,97000 Km,First Owner,2009,150000
1516,Maruti Suzuki Ritz VDi 2009,Diesel,10800 Km,Second Owner,2009,235000

In [20]:
# saving data
df.to_csv('DroomCars.csv', index=False)